export class form {

  static subcellularLocations: string[] = ['',
    'Beyond chloroplast Inner envelope',
    'Cell wall (GFP)',
    'Cytosol',
    'Cytosol, Homomeric',
    'Cytosolic (GFP)',
    'Endomembrane',
    'Endomembrane (GFP)',
    'Endomembrane (proteomics)',
    'Extracellular',
    'Mitochondria',
    'Mitochondria (in vitro import and western blot on subcellular fractions) and Enc',
    'Nuclear',
    'Oilbody',
    'Peroxisome',
    'Plasma membrane (GFP)',
    'Plasma membrane (proteomics)',
    'Plastid',
    'Plastid envelope',
    'Plastid envelope: proteomics',
    'Plastid inner envelop and thylakoid membranes',
    'Plastid inner envelope',
    'Plastid, Homorneric',
    'Vacuole (proteomics), Endomembrane (GFP)',
  ];
  static evidenceForFunction: string[] = [
    '',
    'Mutant Char., Heterol Exp\'n.; in-planta Overexp\'n.',
    'Biochem. assay; Seq. Similarity',
    'Compl. of E. coli mutant',
    'Comple. of yeast mutant',
    'Heterol Exp\'n.',
    'Heterol Exp\'n, in planta Overexpn',
    'Heterol Exp\'n; Comple. of yeast mutant',
    'Heterol Exp\'n; Mutant Char.',
    'Heterol Exp\'n; RNAI',
    'Heterol Exp\'n. RNA lines',
    'Heterol Exp\'n; Seq, Similarity',
    'In vitro assay',
    'in-planta Overexpn.',
    'Lipid Signaling',
    'Miscellaneous',
    'Mutant Char.',
    'Mutant Char,, Comple. of E. coli mutant, Heterol Exp\'n; Seq. Similarity',
    'Mutant Char, Heterol Expn.; Comple. of yeast mutant',
    'Mutant Char, Heterol Exp\'n; in-planta OverExp\'n.',
    'Mutant Char, in-planta Overexpn.; Seq. Similarity',
    'Mutant Char; biochemical activity in E. coli; Complementation',
    'Mutant Char; Comple. of bacterial gpsA mutant',
    'Mutant Char; Comple. of E. coli mutant; Heterol Exp\'n.',
    'Mutant Char.; Comple. of mutant',
    'Mutant Char.; Comple. of yeast mutant',
    'Mutant Char; Heterol Exp\'n.',
    'Mutant Char; Heterol Exp\'n. in vitro assays',
    'Mutant Char; Heterol Exp\'n; in-planta OverExp\'n.',
    'Mutant Char; Heterol Exp\'n. Seq. Similarity',
    'Mutant Char; in-planta OverExp\'n.',
    'Mutant Char.; in-planta Overexpn.; Comple. of yeast mutants',
    'Mutant Char; in-planta Overexpn,; RNAI lines',
    'Mutant Char; in-planta Overexprn.',
    'Mutant Char; RNA lines; Seq. Similarity',
    'Mutant Char; RNAI; Comple. of yeast mutant',
    'Mutant Char; RNAV; Seq. Similarity',
    'Mutant Char; Seq. Similarity',
    'Mutant Char; in-planta OverExp\'n.',
    'Mutant Char.; in-planta Overexpn.; Comple. of yeast mutants',
    'RNA lines; in -planta Overexpn.; Seq. Similarity',
    'Seq. Similarity',
    'Seq. Similarity to CER4',
    'Seq. Similarity; Heterol Exp\'n.',
    'Seq. Similarity; upregulated in epidermis',
  ];
  static pathways: string[] = ['',
    'Cutin Synthesis & Transport 1 Of 2',
    'Cutin Synthesis & Transport 2 Of 2',
    'Eukaryotic Galactolipid & Sulfolipid Synthesis',
    'Eukaryotic Phospholipid Synthesis & Editing',
    'Fatty Acid Elongation & Wax Biosynthesis',
    'Fatty Acid Elongation, Desaturation & Export From Plastid',
    'Fatty Acid Synthesis',
    'Glycolipid Head Group Structures',
    'Lipid Trafficking',
    'Main Classes Of Storage & Membrane Lipid Structures',
    'Miscellaneous',
    'Mitochondrial Fatty Acid & Lipoic Acid Synthesis',
    'Mitochondrial Phospholipid Synthesis',
    'Oxylipin Metabolism 1 Of 2',
    'Oxylipin Metabolism 2 Of 2',
    'Pathways',
    'Phospholipid Head Group Structures',
    'Phospholipid Signaling',
    'Prokaryotic Galactolipid, Sulfolipid, & Phospholipid Synthesis 1 Of 2',
    'Prokaryotic Galactolipid, Sulfolipid, & Phospholipid Synthesis 2 Of 2',
    'Sphingolipid Biosynthesis 1 Of 2',
    'Sphingolipid Biosynthesis 2 Of 2',
    'Sphingolipid Sample Structure',
    'Structure Of Major Arabidopsis Fatty Acids',
    'Suberin Synthesis & Transport 1 Of 3',
    'Suberin Synthesis & Transport 2 Of 3',
    'Suberin Synthesis & Transport 3 Of 3',
    'Triacvlalveerol & Eattv Acid Dearadation',
    'Triacylglycerol Biosynthesis',
  ];

    constructor(
      public name: string,
      public affiliation: string,
      public email_address: string,
      public record_type: string,
      public record_url?: string, 
      public figure_url?: string, 
      public pathway?: string,  
      public protein_family_name_common?: string, 
      public protein_family_abbreviation_common?: string,  
      public isoform_gene_name?: string,  
      public isoform_gene_abbreviation?: string,  
      public gene_locus?: string, 
      public ec_number?: string,  
      public subcellular_location_listed?: string,  
      public subcellular_location_filled?: string,  
      public mutant_name?: string,  
      public evidence_for_function_listed?: string,  
      public evidence_for_function_filled?: string,  
      public specific_comments_on_locus?: string, 
      public other_comments?: string,  
      public reference_1?: string,  
      public pubmed_link_1?: string,
      public reference_2?: string,  
      public pubmed_link_2?: string, 
      public reference_3?: string,  
      public pubmed_link_3?: string  
    ) {}
  }
  